 
****************************************
Report : resources
Design : MIPS
Version: R-2020.09
Date   : Mon Dec 23 15:13:38 2024
****************************************


Resource Report for this hierarchy in file
        /mnt/newNAS/home/UnderGraduate2/2024/macplanck/VLSI/GPT_MIPS/02_SYN/MIPS.sv
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| add_x_9        | DW01_add       | width=32   | add_73 (MIPS.sv:73)        |
| lt_x_13        | DW_cmp         | width=32   | ALU/lt_124 (MIPS.sv:124)   |
=============================================================================


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| add_x_9            | DW01_add         | pparch (area,speed)                 |
===============================================================================

1
